# NumPy

NumPy (ou Numpy) é uma biblioteca de álgebra linear para Python, a razão pela qual é tão importante para a Data Science com Python é que quase todas as bibliotecas dependem do NumPy como um dos seus principais blocos de construção.

Numpy também é incrivelmente rápido, pois tem ligações para bibliotecas C. Para obter mais informações sobre por que você deseja usar Arrays em vez de listas, confira esta excelente publicação do [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

Nós só aprenderemos os conceitos básicos do NumPy, para começar, precisamos instalá-lo!

## Instruções de instalação

** É altamente recomendável que instale o Python usando a distribuição da Anaconda para garantir que todas as dependências subjacentes (como as bibliotecas de Álgebra Linear) se sincronizem com o uso de uma instalação conda. Se você tiver o Anaconda, instale o NumPy acessando seu terminal ou prompt de comando e digite: **

    conda install numpy
    
** Se você não possui Anaconda e não pode instalá-lo, consulte: [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Usando NumPy

Depois de instalar o NumPy, você pode importá-lo como uma biblioteca:

In [1]:
import numpy as np

Numpy possui muitas funções e capacidades incorporadas. Não vamos cobri-los na totalidade, mas, em vez disso, vamos nos concentrar em alguns dos aspectos mais importantes de Numpy: vetores, arrays, matrizes e geração de números. Comecemos por arrays:

# Numpy Arrays

As matrizes de NumPy são a maneira principal de usar Numpy ao longo do curso. Numpy arrays essencialmente vêm de duas formas: vetores e matrizes. Os vetores são estritamente arranjos de 1d e as matrizes são 2d (mas você deve observar que uma matriz ainda pode ter apenas uma linha ou uma coluna).

Vamos começar nossa introdução explorando como criar matrizes numPy.


## Criando NumPy Arrays

### De uma lista de Python

Podemos criar uma matriz convertendo diretamente uma lista ou lista de listas:

In [2]:
minha_lista = [1,2,3]
minha_lista

[1, 2, 3]

In [4]:
np.array(minha_lista)

array([1, 2, 3])

In [5]:
minha_matriz = [[1,2,3],[4,5,6],[7,8,9]]
minha_matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Métodos incorporados (Built-in Methods)

Há muitas maneiras embutidas de gerar Arrays

### arange

Retorna valores uniformemente espaçados dentro de um determinado intervalo.

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros e ones

Gerar matrizes de zeros ou de ums

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Retorna números uniformemente espaçados ao longo de um intervalo especificado.

In [ ]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

## eye

Cria uma matriz identidade

In [8]:
identidade = np.eye(4)

In [12]:
identidade.reshape(2,8)

array([[1., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1.]])

## Random

Numpy também tem muitas maneiras de criar arrays de números aleatórios:

### rand
Cria uma matriz da forma dada e preencha com amostras aleatórias de uma distribuição uniforme sobre ``[0, 1)``.

In [ ]:
np.random.rand(2)

array([0.61618515, 0.94216489])

In [ ]:
np.random.rand(5,2)

array([[0.30542544, 0.37964896],
       [0.74747895, 0.62341379],
       [0.45872042, 0.96422335],
       [0.77014921, 0.60326707],
       [0.1514344 , 0.81002125]])

### randn

Retorna uma amostra (ou amostras) da distribuição "normal". Ao contrário de rand, que é uniforme:
https://pt.wikipedia.org/wiki/Distribui%C3%A7%C3%A3o_normal

![image.png](attachment:image.png)

In [ ]:
np.random.randn(2)

array([ 0.46378055, -1.23165322])

In [ ]:
np.random.randn(5,5)

array([[ 2.07502733,  1.04521276,  0.51907289,  0.42358284,  1.27303754],
       [ 0.9118794 ,  1.02910736, -0.37555439,  0.9955875 , -1.06749879],
       [ 0.75514353, -0.52208633, -1.11308528,  1.53645129,  0.27384693],
       [ 0.84286208,  0.78384267,  0.32124887, -1.01791632, -0.2583003 ],
       [-1.16711011,  0.74355411, -1.97948343,  1.47945848, -0.24022146]])

### randint
Retorna inteiros aleatórios de "low" (inclusive) para "high" (exclusivo).

In [ ]:
#np.random.randint(low, high)
np.random.randint(1,100)

95

In [ ]:
np.random.randint(1,100,10)

array([33, 30, 82, 37,  2, 57, 10, 24, 24, 71])

## Atributos de Array e Métodos

Vamos discutir alguns atributos e métodos úteis ou uma matriz:

In [ ]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr

array([13, 39, 41, 14, 29, 29, 43, 16, 44, 44])

## Reshape
Retorna uma matriz contendo os mesmos dados com uma nova forma.

In [ ]:
arr.shape

(25,)

In [ ]:
arr2 = arr.reshape(5,5)

In [ ]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr2 @ arr2

array([[ 150,  160,  170,  180,  190],
       [ 400,  435,  470,  505,  540],
       [ 650,  710,  770,  830,  890],
       [ 900,  985, 1070, 1155, 1240],
       [1150, 1260, 1370, 1480, 1590]])

### max,min,argmax,argmin

Estes são métodos úteis para encontrar valores máximos ou mínimos, ou para encontrar seus locais de índice usando argmin ou argmax

In [ ]:
ranarr

array([26, 34, 46, 46, 34, 47, 18, 33, 30, 22])

In [ ]:
ranarr.max()

47

In [ ]:
ranarr.argmax()

5

In [ ]:
ranarr.min()

13

In [ ]:
ranarr.argmin()

0

## Shape

Shape é um atributo que os arrays têm (não um método):

In [7]:
# Vector
arr.shape

NameError: name 'arr' is not defined

In [ ]:
arr.reshape(1,25)

NameError: name 'arr' is not defined

In [ ]:
arr.reshape(1,25).shape

NameError: name 'arr' is not defined

In [ ]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
arr.reshape(25,1).shape

(25, 1)

### dtype
Você também pode pegar o tipo de dados do objeto na matriz:

In [ ]:
arr.dtype

dtype('int64')