In [1]:
import numpy as np

In [3]:


def vandermonde(x, y):
    num_points = x.shape[0]
    A = np.zeros((num_points, num_points), np.float64)

    for i in range(num_points):
        for j in range(num_points):
            A[i, j] = x[i] ** j

    coef = np.linalg.inv(A) @ np.transpose(y)

    return coef



In [4]:

# Exemplo 6.1, 6.2, 6.3
x = np.array([1.5, 3.5, 7., 11.5, 14])
y = np.array([3, 6, 2.5, 9.5, 7.4])
x_interpol = 10

# Retorna Coeficientes do Polinômio
coefs_vander = vandermonde(x, y)


print('Polinômio obtido método de Vandermonde')
print(round(coefs_vander[0], 6)),
for i in range(1, len(coefs_vander)):
    print(f'{round(coefs_vander[i], 6)}x^{i}'),

Polinômio obtido método de Vandermonde
-9.228203
12.500419x^1
-3.385649x^2
0.341379x^3
-0.011233x^4


In [6]:
num_points = x.shape[0]
num_points


5

In [7]:
A = np.zeros((num_points, num_points), np.float64)
A

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
# x = ([1.5, 3.5, 7., 11.5, 14])
for i in range(num_points):
        for j in range(num_points):
            A[i, j] = x[i] ** j
A

array([[1.00000000e+00, 1.50000000e+00, 2.25000000e+00, 3.37500000e+00,
        5.06250000e+00],
       [1.00000000e+00, 3.50000000e+00, 1.22500000e+01, 4.28750000e+01,
        1.50062500e+02],
       [1.00000000e+00, 7.00000000e+00, 4.90000000e+01, 3.43000000e+02,
        2.40100000e+03],
       [1.00000000e+00, 1.15000000e+01, 1.32250000e+02, 1.52087500e+03,
        1.74900625e+04],
       [1.00000000e+00, 1.40000000e+01, 1.96000000e+02, 2.74400000e+03,
        3.84160000e+04]])

In [9]:
# Computes the inverse of the Vandermonde matrix A.
b= np.linalg.inv(A)
b

array([[ 2.86872727e+00, -2.87500000e+00,  1.39393939e+00,
        -5.71666667e-01,  1.84000000e-01],
       [-1.68381818e+00,  2.78273810e+00, -1.54834055e+00,
         6.66944444e-01, -2.17523810e-01],
       [ 3.29636364e-01, -6.60289116e-01,  4.84436199e-01,
        -2.31388889e-01,  7.76054422e-02],
       [-2.61818182e-02,  5.78231293e-02, -5.02989074e-02,
         2.88888889e-02, -1.02312925e-02],
       [ 7.27272727e-04, -1.70068027e-03,  1.64914451e-03,
        -1.11111111e-03,  4.35374150e-04]])

In [10]:
# y = np.array([3, 6, 2.5, 9.5, 7.4])
c = np.transpose(y)
c

array([3. , 6. , 2.5, 9.5, 7.4])

In [12]:
coef = b @ c
coef

array([-9.22820303e+00,  1.25004187e+01, -3.38564928e+00,  3.41378932e-01,
       -1.12331890e-02])